language: c
sudo: required
services:
  - docker
addons:
  apt:
    packages:
      - bar
      - moreutils
notifications:
  email: false
script:
   - travis_wait docker build .
#  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
#  - mispipe "docker build -t tkelman/docker-gcc-bisect ." bar > build.log || tail -c 2097152 build.log
#- docker push tkelman/docker-gcc-bisect
